// examples/vue/src/App.vue
<script setup lang="ts">
import { computed } from 'vue';

const { t, setLang, currentLang, langs } = useI18n();
const currentLanguageLabel = computed(
  () =>
    langs.value.find(({ value }) => value === currentLang.value)?.label ??
    currentLang.value,
);
</script>

<template>
  <main class="demo-app">
    <header class="demo-header">
      <div class="header-titles">
        <p class="demo-eyebrow">useI18n · Vue 3</p>
        <h1>{{ t('Vue 示例') }}</h1>
      </div>
      <div class="header-controls">
        <label class="language-control">
          <span class="sr-only">{{ t('语言') }}</span>
          <select
            :value="currentLang"
            @change="setLang(($event.target as HTMLSelectElement).value)"
          >
            <option v-for="lang in langs" :key="lang.value" :value="lang.value">
              {{ lang.label }}
            </option>
          </select>
        </label>
      </div>
    </header>

    <section class="demo-panel" :aria-label="t('交互式语言切换演示')">
      <article class="demo-card">
        <span class="demo-label">{{ t('当前语言') }}</span>
        <div class="locale-readout" aria-live="polite">
          <span class="status-dot" aria-hidden="true"></span>
          <strong>{{ currentLanguageLabel }}</strong>
          <code>{{ currentLang }}</code>
        </div>
      </article>

      <article class="demo-card demo-card--highlight">
        <span class="demo-label">{{ t('文案变化') }}</span>
        <div class="translation-output" aria-live="polite">
          <p>{{ t('响应式文案会随语言立即更新') }}</p>
          <span>{{ t('模板会自动响应 Runtime 状态。') }}</span>
        </div>
      </article>
    </section>
  </main>
</template>

// examples/react/src/App.tsx
function App() {
  const { t, setLang, currentLang, langs } = useI18n();
  const currentLanguage = langs.find(({ value }) => value === currentLang);

  return (
    <main className="demo-app">
      <header className="demo-header">
        <div className="header-titles">
          <p className="demo-eyebrow">useI18n · React</p>
          <h1>{t('React 示例')}</h1>
        </div>
        <div className="header-controls">
          <label className="language-control">
            <span className="sr-only">{t('语言')}</span>
            <select
              value={currentLang}
              onChange={(e) => void setLang(e.target.value)}
            >
              {langs.map(({ value, label }) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </select>
          </label>
        </div>
      </header>

      <section className="demo-panel" aria-label={t('交互式语言切换演示')}>
        <article className="demo-card">
          <span className="demo-label">{t('当前语言')}</span>
          <div className="locale-readout" aria-live="polite">
            <span className="status-dot" aria-hidden="true" />
            <strong>{currentLanguage?.label ?? currentLang}</strong>
            <code>{currentLang}</code>
          </div>
        </article>

        <article className="demo-card demo-card--highlight">
          <span className="demo-label">{t('文案变化')}</span>
          <div className="translation-output" aria-live="polite">
            <p>{t('切换后，这段文案会立即更新。')}</p>
            <span>{t('useI18n 实时订阅 Runtime 并重渲染。')}</span>
          </div>
        </article>
      </section>
    </main>
  );
}

export default App;
